openapi: 3.0.0
info:
  title: Simple API
  description: This is a simple API example for demonstrating Redoc documentation.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1
    description: Production server

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string

security:
  - ApiKeyAuth: []

paths:
  /pets:
    get:
      summary: List all pets
      description: Retrieve a list of all available pets.
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
      security:
        - ApiKeyAuth: []

  /pets/{petId}:
    get:
      summary: Info for a specific pet
      description: Retrieve information about a specific pet by ID.
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
      security:
        - ApiKeyAuth: []
